import os
import json
import logging
from typing import Optional, Dict, Any, List
import requests

from utils import setup_logging, read_env, get_env

log = logging.getLogger("confluence")


# -----------------------------
#  Authentication Helper
# -----------------------------
def _auth(user: str, token: str):
    return (user, token)


# -----------------------------
#  Page Creation / Retrieval
# -----------------------------
def get_page_by_title(base: str, user: str, token: str, space: str, title: str) -> Optional[Dict[str, Any]]:
    url = f"{base}/rest/api/content"
    params = {"spaceKey": space, "title": title, "expand": "version,ancestors"}
    r = requests.get(url, params=params, auth=_auth(user, token))
    r.raise_for_status()
    results = r.json().get("results", [])
    return results[0] if results else None


def create_page(base: str, user: str, token: str, space: str, title: str, body_html: str,
                parent_title: Optional[str] = None) -> Dict[str, Any]:
    payload = {
        "type": "page",
        "title": title,
        "space": {"key": space},
        "body": {"storage": {"value": body_html, "representation": "storage"}}
    }
    if parent_title:
        parent = get_page_by_title(base, user, token, space, parent_title)
        if parent:
            payload["ancestors"] = [{"id": parent["id"]}]
    url = f"{base}/rest/api/content"
    r = requests.post(url, auth=_auth(user, token), json=payload)
    r.raise_for_status()
    log.info(f"✅ Created new Confluence page: {title}")
    return r.json()


# -----------------------------
#  File Attachment Handling
# -----------------------------
def attach_file(base: str, user: str, token: str, page_id: str, file_path: str) -> Dict[str, Any]:
    """
    Upload or update a file on a Confluence page. Works with Confluence Cloud REST API.
    """
    headers = {"X-Atlassian-Token": "no-check"}
    auth = _auth(user, token)
    filename = os.path.basename(file_path)
    url = f"{base}/rest/api/content/{page_id}/child/attachment"

    file_path = file_path.replace("\\", "/")

    # check if file already exists
    existing = requests.get(url, auth=auth)
    existing.raise_for_status()
    attachments = existing.json().get("results", [])
    existing_attachment = next((a for a in attachments if a["title"] == filename), None)

    with open(file_path, "rb") as f:
        files = {"file": (filename, f, "application/octet-stream")}
        if existing_attachment:
            attach_id = existing_attachment["id"]
            update_url = f"{base}/rest/api/content/{page_id}/child/attachment/{attach_id}/data"
            r = requests.post(update_url, auth=auth, headers=headers, files=files)
            if r.status_code not in (200, 201):
                raise Exception(f"Failed to update attachment {filename}: {r.status_code} {r.text}")
            log.info(f"🔁 Updated existing attachment: {filename}")
        else:
            r = requests.post(url, auth=auth, headers=headers, files=files)
            if r.status_code not in (200, 201):
                raise Exception(f"Failed to upload new attachment {filename}: {r.status_code} {r.text}")
            log.info(f"✅ Uploaded new attachment: {filename}")

    return {"file": filename, "status": "uploaded"}


# -----------------------------
#  URL and Version Utilities
# -----------------------------
def page_url(base: str, page_id: str, space: str) -> str:
    return f"{base}/spaces/{space}/pages/{page_id}"


def next_version_number(version_file: str = "report/version.txt") -> int:
    os.makedirs(os.path.dirname(version_file), exist_ok=True)
    if os.path.exists(version_file):
        with open(version_file) as f:
            try:
                return int(f.read().strip()) + 1
            except ValueError:
                pass
    return 1


def write_version(version_file: str, version: int):
    with open(version_file, "w") as f:
        f.write(str(version))


# -----------------------------
#  Main Entry Point
# -----------------------------
def main():
    setup_logging()
    read_env()

    base = get_env("CONFLUENCE_BASE", required=True).rstrip("/")
    user = get_env("CONFLUENCE_USER", required=True)
    token = get_env("CONFLUENCE_TOKEN", required=True)
    space = get_env("CONFLUENCE_SPACE", required=True)
    title = get_env("CONFLUENCE_TITLE", required=True)
    parent_title = os.getenv("CONFLUENCE_PARENT_TITLE", "").strip() or None

    report_dir = os.getenv("REPORT_DIR", "report")
    version_file = os.path.join(report_dir, "version.txt")

    version = next_version_number(version_file)
    write_version(version_file, version)
    versioned_title = f"{title} v{version}"

    body_html = (
        f"<p><b>Automated Test Report</b> for version <b>v{version}</b>.</p>"
        f"<p>Generated by Jenkins CI pipeline.</p>"
        f"<p>Attached below are the test result files.</p>"
    )

    # create page
    created = create_page(base, user, token, space, versioned_title, body_html, parent_title)
    page_id = created["id"]
    link = page_url(base, page_id, space)

    # attach files
    if os.path.isdir(report_dir):
        for name in os.listdir(report_dir):
            fpath = os.path.join(report_dir, name)
            if os.path.isfile(fpath) and not name.endswith(".gitkeep"):
                try:
                    attach_file(base, user, token, page_id, fpath)
                except Exception as e:
                    log.warning(f"❌ Attach failed for {fpath}: {e}")

    print(json.dumps({"page_id": page_id, "link": link, "version": version}, indent=2))


if __name__ == "__main__":
    main()
